plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/studioknodel/Library/CloudStorage/GoogleDrive-studioknodel@gmail.com/My Drive/Claude/World Cup"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]